### ISSUE TITLE
Typo found

### ISSUE THREAD

**Issue by arro-mts** [yialo/css-common-classnames#1]
1. [warnin**n**g](https://github.com/yialo/css-common-classnames#%D0%BF%D1%80%D0%B5%D0%B4%D1%83%D0%BF%D1%80%D0%B5%D0%B6%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5)
2. [nic**h**name](https://github.com/yialo/css-common-classnames#%D0%BD%D0%B8%D0%BA)

**Comment by yialo** [comment]
Fixed.
